name: "Dockerfile build"
on: 
  workflow_dispatch:
  # For now, only run on requests, not the main branches.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build Docker image"
      run: docker build .
